# Generated by Django 4.1.3 on 2022-11-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='thumb',
            field=models.ImageField(upload_to='thumb_filmes'),
        ),
    ]
